Fix java.base add opens getting lost if sole entry
JBoss Threads opens java.base to org.jboss.threads and this got lost,
thus causing the usual warning in Quarkus:

java.lang.IllegalAccessError: module java.base does not open java.lang to module org.jboss.threads; to use the thread-local-reset capability on Java 24 or later, use this JVM option: --add-opens java.base/java.lang=org.jboss.threads

coming from org.jboss.threads.JDKSpecific$ThreadAccess.<clinit>.

Problem is that the dependency was merged into the preexisting java.base
entry from INITIAL_DEP_MAP and thus size of the Map was still 1, thus
causing the Map to be reinitialized.